### ISSUE TITLE
공유 받은 URL 로 접속했을 시, 무조건 실패하는 socket 접속요청을 보냄

### ISSUE THREAD

**Issue by JeongJaeSoon** [2P3S/scrum-dice#84]
url 공유 받았을 때 아무 데이터가 없는 상태로 소켓 접속요청을 보내서, 무조건 에러가 발생함
방 or 멤버 아이디가 없을때는 소켓접속 요청을 보내지 않게한다

**Comment by hyunnnn98** [comment]
유저 정보가 없는 경우에는 비회원 로그인 페이지로 `redirection` 하는 로직을 추가하여 해결.
https://github.com/2P3S/2p3s-scrum-dice/blob/develop/src/pages/room/%5Bid%5D.tsx#L49-L52
